package pro.sketchware.designer;

import java.util.ArrayList;
import java.util.List;

/**
 * Writes one model class per table for Firebase Realtime Database data. The project's Firebase blocks read and write
 * maps ({@code HashMap<String, Object>}), so each class converts to and from such a map. It uses no Firebase class,
 * so it compiles whether Firebase is enabled or not. Java 7.
 */
public final class FirebaseModelGenerator {
    private FirebaseModelGenerator() {
    }

    public static String check(String packageName, List<DesignSpec.Table> tables) {
        if (!Identifiers.isPackageName(packageName)) return "The package name is not valid";
        for (DesignSpec.Table table : tables) {
            for (DesignSpec.Field field : table.fields()) {
                if (field.type() == FieldType.BLOB) return "Firebase Realtime Database cannot store blob fields (" + table.name() + "." + field.name() + ")";
            }
        }
        return null;
    }

    public static List<Generated> generate(String packageName, List<DesignSpec.Table> tables) {
        String error = check(packageName, tables);
        if (error != null) throw new IllegalArgumentException(error);
        List<Generated> files = new ArrayList<>();
        for (DesignSpec.Table table : tables) {
            files.add(new Generated(table.name() + ".java", model(packageName, table)));
        }
        return files;
    }

    private static String model(String packageName, DesignSpec.Table table) {
        String t = table.name();
        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import java.util.HashMap;\nimport java.util.Map;\n\n");
        out.append("/**\n * Model generated by the data designer. {@code toMap()} gives what the Firebase blocks write, and\n");
        out.append(" * {@code fromMap(map)} reads what they return. {@code key} is the child's key and is not stored as a field.\n */\n");
        out.append("public class ").append(t).append(" {\n");
        out.append("    public String key;\n");
        for (DesignSpec.Field field : table.fields()) {
            out.append("    public ").append(field.type().javaType).append(' ').append(field.name()).append(";\n");
        }
        out.append("\n    public ").append(t).append("() {\n    }\n\n");
        out.append("    public HashMap<String, Object> toMap() {\n");
        out.append("        HashMap<String, Object> map = new HashMap<String, Object>();\n");
        for (DesignSpec.Field field : table.fields()) {
            out.append("        map.put(").append(Identifiers.quote(field.name())).append(", ").append(field.name()).append(");\n");
        }
        out.append("        return map;\n    }\n\n");
        out.append("    /** Reads a map from the Firebase blocks; missing or mistyped values keep their default. */\n");
        out.append("    public static ").append(t).append(" fromMap(String key, Map<String, Object> map) {\n");
        out.append("        ").append(t).append(" item = new ").append(t).append("();\n");
        out.append("        item.key = key;\n");
        out.append("        if (map == null) {\n            return item;\n        }\n");
        for (DesignSpec.Field field : table.fields()) {
            String get = "map.get(" + Identifiers.quote(field.name()) + ")";
            String name = field.name();
            switch (field.type()) {
                case TEXT -> out.append("        if (").append(get).append(" != null) {\n            item.").append(name)
                        .append(" = String.valueOf(").append(get).append(");\n        }\n");
                case INT -> out.append("        if (").append(get).append(" instanceof Number) {\n            item.").append(name)
                        .append(" = ((Number) ").append(get).append(").longValue();\n        }\n");
                case REAL -> out.append("        if (").append(get).append(" instanceof Number) {\n            item.").append(name)
                        .append(" = ((Number) ").append(get).append(").doubleValue();\n        }\n");
                case BOOL -> out.append("        if (").append(get).append(" instanceof Boolean) {\n            item.").append(name)
                        .append(" = (Boolean) ").append(get).append(";\n        }\n");
                case BLOB -> {
                }
            }
        }
        out.append("        return item;\n    }\n}\n");
        return out.toString();
    }
}
