package pro.sketchware.designer;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Writes a small REST client: one method per request, run on a background thread with HttpURLConnection, with the
 * answer handed back on the main thread. Only the Android SDK and Java 7 are used. Path parameters are URL-encoded.
 */
public final class RestClientGenerator {
    private static final Pattern PATH_PARAM = Pattern.compile("\\{([^}/]*)\\}");

    private RestClientGenerator() {
    }

    public static String check(String packageName, String className, String baseUrl, List<DesignSpec.Endpoint> endpoints) {
        if (!Identifiers.isPackageName(packageName)) return "The package name is not valid";
        if (!Identifiers.isJavaName(className)) return "The class name is not valid";
        if (baseUrl == null || !baseUrl.matches("https?://[^\\s\"]+")) return "The base address must start with https:// (or http://)";
        for (DesignSpec.Endpoint endpoint : endpoints) {
            if (endpoint.name().equals(className)) return "A request cannot have the same name as the class";
        }
        return null;
    }

    /** Java expression building the path: literal parts quoted, parameters encoded. */
    static String pathExpression(String path) {
        StringBuilder out = new StringBuilder();
        Matcher matcher = PATH_PARAM.matcher(path);
        int last = 0;
        while (matcher.find()) {
            if (matcher.start() > last) {
                if (out.length() > 0) out.append(" + ");
                out.append(Identifiers.quote(path.substring(last, matcher.start())));
            }
            if (out.length() > 0) out.append(" + ");
            out.append("encode(").append(matcher.group(1)).append(')');
            last = matcher.end();
        }
        if (last < path.length() || out.length() == 0) {
            if (out.length() > 0) out.append(" + ");
            out.append(Identifiers.quote(path.substring(last)));
        }
        return out.toString();
    }

    public static Generated generate(String packageName, String className, String baseUrl, List<DesignSpec.Endpoint> endpoints) {
        String error = check(packageName, className, baseUrl, endpoints);
        if (error != null) throw new IllegalArgumentException(error);
        String base = baseUrl.endsWith("/") ? baseUrl.substring(0, baseUrl.length() - 1) : baseUrl;
        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import android.os.Handler;\nimport android.os.Looper;\n\n");
        out.append("import java.io.ByteArrayOutputStream;\nimport java.io.InputStream;\nimport java.io.OutputStream;\n");
        out.append("import java.io.UnsupportedEncodingException;\nimport java.net.HttpURLConnection;\nimport java.net.URL;\n");
        out.append("import java.net.URLEncoder;\nimport java.util.LinkedHashMap;\nimport java.util.Map;\n");
        out.append("import java.util.concurrent.ExecutorService;\nimport java.util.concurrent.Executors;\n\n");
        out.append("/**\n * REST client generated by the data designer. Each method sends its request on a background thread and\n");
        out.append(" * calls the callback on the main thread, so the callback may update views. Needs the INTERNET permission.\n */\n");
        out.append("public class ").append(className).append(" {\n");
        out.append("    public static final String BASE_URL = ").append(Identifiers.quote(base)).append(";\n\n");
        out.append("    public interface Callback {\n");
        out.append("        /** Any answer from the server, also an error status like 404; {@code body} is the text of the answer. */\n");
        out.append("        void onResponse(int code, String body);\n\n");
        out.append("        /** No answer: no network, a wrong address, a timeout... */\n");
        out.append("        void onFailure(Exception error);\n    }\n\n");
        out.append("    private final String baseUrl;\n");
        out.append("    private final Map<String, String> headers = new LinkedHashMap<String, String>();\n");
        out.append("    private final ExecutorService executor = Executors.newSingleThreadExecutor();\n");
        out.append("    private final Handler mainThread = new Handler(Looper.getMainLooper());\n");
        out.append("    private int timeoutMillis = 15000;\n\n");
        out.append("    public ").append(className).append("() {\n        this(BASE_URL);\n    }\n\n");
        out.append("    public ").append(className).append("(String baseUrl) {\n        this.baseUrl = baseUrl;\n    }\n\n");
        out.append("    /** Sent with every request, like an Authorization header. */\n");
        out.append("    public void setHeader(String name, String value) {\n");
        out.append("        synchronized (headers) {\n            headers.put(name, value);\n        }\n    }\n\n");
        out.append("    public void setTimeoutMillis(int timeoutMillis) {\n        this.timeoutMillis = timeoutMillis;\n    }\n\n");
        out.append("    /** Stops the background thread; call it when the screen is closed. */\n");
        out.append("    public void shutdown() {\n        executor.shutdown();\n    }\n");
        for (DesignSpec.Endpoint endpoint : endpoints) {
            out.append('\n');
            out.append("    /** ").append(endpoint.method()).append(' ').append(endpoint.path().replace("*/", "* /")).append(" */\n");
            out.append("    public void ").append(endpoint.name()).append('(');
            for (String param : endpoint.pathParams()) out.append("String ").append(param).append(", ");
            if (endpoint.hasBody()) out.append("String body, ");
            out.append("Callback callback) {\n");
            out.append("        send(\"").append(endpoint.method()).append("\", ").append(pathExpression(endpoint.path())).append(", ")
                    .append(endpoint.hasBody() ? "body" : "null").append(", callback);\n    }\n");
        }
        out.append("""

                    private static String encode(String value) {
                        try {
                            return URLEncoder.encode(value == null ? "" : value, "UTF-8").replace("+", "%20");
                        } catch (UnsupportedEncodingException e) {
                            throw new IllegalStateException(e);
                        }
                    }

                    private void send(final String method, final String path, final String body, final Callback callback) {
                        final Map<String, String> requestHeaders;
                        synchronized (headers) {
                            requestHeaders = new LinkedHashMap<String, String>(headers);
                        }
                        executor.execute(new Runnable() {
                            @Override
                            public void run() {
                                HttpURLConnection connection = null;
                                try {
                                    URL url = new URL(path.startsWith("http") ? path : baseUrl + path);
                                    connection = (HttpURLConnection) url.openConnection();
                                    connection.setRequestMethod(method);
                                    connection.setConnectTimeout(timeoutMillis);
                                    connection.setReadTimeout(timeoutMillis);
                                    for (Map.Entry<String, String> header : requestHeaders.entrySet()) {
                                        connection.setRequestProperty(header.getKey(), header.getValue());
                                    }
                                    if (body != null) {
                                        if (connection.getRequestProperty("Content-Type") == null) {
                                            connection.setRequestProperty("Content-Type", "application/json; charset=utf-8");
                                        }
                                        connection.setDoOutput(true);
                                        OutputStream output = connection.getOutputStream();
                                        try {
                                            output.write(body.getBytes("UTF-8"));
                                        } finally {
                                            output.close();
                                        }
                                    }
                                    final int code = connection.getResponseCode();
                                    InputStream input = code >= 400 ? connection.getErrorStream() : connection.getInputStream();
                                    final String text = input == null ? "" : read(input);
                                    mainThread.post(new Runnable() {
                                        @Override
                                        public void run() {
                                            callback.onResponse(code, text);
                                        }
                                    });
                                } catch (final Exception e) {
                                    mainThread.post(new Runnable() {
                                        @Override
                                        public void run() {
                                            callback.onFailure(e);
                                        }
                                    });
                                } finally {
                                    if (connection != null) {
                                        connection.disconnect();
                                    }
                                }
                            }
                        });
                    }

                    private static String read(InputStream input) throws java.io.IOException {
                        try {
                            ByteArrayOutputStream bytes = new ByteArrayOutputStream();
                            byte[] buffer = new byte[8192];
                            int count;
                            while ((count = input.read(buffer)) != -1) {
                                bytes.write(buffer, 0, count);
                            }
                            return bytes.toString("UTF-8");
                        } finally {
                            input.close();
                        }
                    }
                }
                """);
        return new Generated(className + ".java", out.toString());
    }
}
