package pro.sketchware.designer;

import java.util.ArrayList;
import java.util.List;

/**
 * Writes a SQLiteOpenHelper with one model class and typed insert, update, delete, get and list methods per table.
 * It plays the part of Room, which cannot work in this IDE's builds because they compile without annotation
 * processing. The code only uses the Android SDK and Java 7, the default language level of projects.
 */
public final class SqliteGenerator {
    private SqliteGenerator() {
    }

    /** @return the error to show, or null when the input can be generated */
    public static String check(String packageName, String className, String databaseName, int version, List<DesignSpec.Table> tables) {
        if (!Identifiers.isPackageName(packageName)) return "The package name is not valid";
        if (!Identifiers.isJavaName(className)) return "The class name is not valid";
        if (databaseName == null || !databaseName.matches("[A-Za-z0-9_.-]+")) return "The database file name may only use letters, digits, _, . and -";
        if (version < 1) return "The version must be 1 or more";
        for (DesignSpec.Table table : tables) {
            if (table.name().equals(className)) return "A table cannot have the same name as the class";
        }
        return null;
    }

    public static Generated generate(String packageName, String className, String databaseName, int version, List<DesignSpec.Table> tables) {
        String error = check(packageName, className, databaseName, version, tables);
        if (error != null) throw new IllegalArgumentException(error);
        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import android.content.ContentValues;\n");
        out.append("import android.content.Context;\n");
        out.append("import android.database.Cursor;\n");
        out.append("import android.database.sqlite.SQLiteDatabase;\n");
        out.append("import android.database.sqlite.SQLiteOpenHelper;\n\n");
        out.append("import java.util.ArrayList;\n");
        out.append("import java.util.List;\n\n");
        out.append("/**\n * Database generated by the data designer. Get it with {@code ").append(className)
                .append(".get(context)}.\n * Run its methods off the main thread for large tables.\n */\n");
        out.append("public class ").append(className).append(" extends SQLiteOpenHelper {\n");
        out.append("    public static final String DATABASE_NAME = ").append(Identifiers.quote(databaseName)).append(";\n");
        out.append("    public static final int DATABASE_VERSION = ").append(version).append(";\n\n");
        out.append("    private static ").append(className).append(" instance;\n\n");
        out.append("    public static synchronized ").append(className).append(" get(Context context) {\n");
        out.append("        if (instance == null) {\n");
        out.append("            instance = new ").append(className).append("(context.getApplicationContext());\n");
        out.append("        }\n");
        out.append("        return instance;\n    }\n\n");
        out.append("    private ").append(className).append("(Context context) {\n");
        out.append("        super(context, DATABASE_NAME, null, DATABASE_VERSION);\n    }\n\n");
        out.append("    @Override\n    public void onCreate(SQLiteDatabase db) {\n");
        for (DesignSpec.Table table : tables) {
            out.append("        db.execSQL(").append(Identifiers.quote(createSql(table))).append(");\n");
        }
        out.append("    }\n\n");
        out.append("    /** Drops and recreates the tables, so stored data is lost: write a real migration before raising the version of a published app. */\n");
        out.append("    @Override\n    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {\n");
        for (DesignSpec.Table table : tables) {
            out.append("        db.execSQL(\"DROP TABLE IF EXISTS ").append(table.name()).append("\");\n");
        }
        out.append("        onCreate(db);\n    }\n");
        for (DesignSpec.Table table : tables) {
            appendTable(out, table);
        }
        out.append("}\n");
        return new Generated(className + ".java", out.toString());
    }

    static String createSql(DesignSpec.Table table) {
        List<String> columns = new ArrayList<>();
        columns.add("id INTEGER PRIMARY KEY AUTOINCREMENT");
        for (DesignSpec.Field field : table.fields()) {
            columns.add(field.name() + " " + field.type().sqlType);
        }
        return "CREATE TABLE " + table.name() + " (" + String.join(", ", columns) + ")";
    }

    private static void appendTable(StringBuilder out, DesignSpec.Table table) {
        String t = table.name();
        String q = Identifiers.quote(t);
        out.append("\n    // ---- ").append(t).append("\n\n");
        out.append("    public static class ").append(t).append(" {\n");
        out.append("        public long id;\n");
        for (DesignSpec.Field field : table.fields()) {
            out.append("        public ").append(field.type().javaType).append(' ').append(field.name()).append(";\n");
        }
        out.append("    }\n\n");
        out.append("    /** Adds {@code item} and sets its id. */\n");
        out.append("    public long insert").append(t).append('(').append(t).append(" item) {\n");
        out.append("        item.id = getWritableDatabase().insert(").append(q).append(", null, values").append(t).append("(item));\n");
        out.append("        return item.id;\n    }\n\n");
        out.append("    /** @return how many rows changed (0 when no row has that id) */\n");
        out.append("    public int update").append(t).append('(').append(t).append(" item) {\n");
        out.append("        return getWritableDatabase().update(").append(q).append(", values").append(t)
                .append("(item), \"id = ?\", new String[]{String.valueOf(item.id)});\n    }\n\n");
        out.append("    public int delete").append(t).append("(long id) {\n");
        out.append("        return getWritableDatabase().delete(").append(q).append(", \"id = ?\", new String[]{String.valueOf(id)});\n    }\n\n");
        out.append("    /** @return the row with that id, or null */\n");
        out.append("    public ").append(t).append(" get").append(t).append("(long id) {\n");
        out.append("        Cursor cursor = getReadableDatabase().query(").append(q)
                .append(", null, \"id = ?\", new String[]{String.valueOf(id)}, null, null, null);\n");
        out.append("        try {\n");
        out.append("            return cursor.moveToFirst() ? read").append(t).append("(cursor) : null;\n");
        out.append("        } finally {\n            cursor.close();\n        }\n    }\n\n");
        out.append("    /** @param orderBy a column to sort by, like \"id DESC\", or null */\n");
        out.append("    public List<").append(t).append("> get").append(t).append("List(String orderBy) {\n");
        out.append("        List<").append(t).append("> items = new ArrayList<").append(t).append(">();\n");
        out.append("        Cursor cursor = getReadableDatabase().query(").append(q).append(", null, null, null, null, null, orderBy);\n");
        out.append("        try {\n");
        out.append("            while (cursor.moveToNext()) {\n");
        out.append("                items.add(read").append(t).append("(cursor));\n");
        out.append("            }\n");
        out.append("        } finally {\n            cursor.close();\n        }\n");
        out.append("        return items;\n    }\n\n");
        out.append("    private static ContentValues values").append(t).append('(').append(t).append(" item) {\n");
        out.append("        ContentValues values = new ContentValues();\n");
        for (DesignSpec.Field field : table.fields()) {
            String key = Identifiers.quote(field.name());
            String value = field.type() == FieldType.BOOL ? "item." + field.name() + " ? 1 : 0" : "item." + field.name();
            out.append("        values.put(").append(key).append(", ").append(value).append(");\n");
        }
        out.append("        return values;\n    }\n\n");
        out.append("    private static ").append(t).append(" read").append(t).append("(Cursor cursor) {\n");
        out.append("        ").append(t).append(" item = new ").append(t).append("();\n");
        out.append("        item.id = cursor.getLong(cursor.getColumnIndexOrThrow(\"id\"));\n");
        for (DesignSpec.Field field : table.fields()) {
            String column = "cursor.getColumnIndexOrThrow(" + Identifiers.quote(field.name()) + ")";
            String read = switch (field.type()) {
                case TEXT -> "cursor.getString(" + column + ")";
                case INT -> "cursor.getLong(" + column + ")";
                case REAL -> "cursor.getDouble(" + column + ")";
                case BOOL -> "cursor.getInt(" + column + ") != 0";
                case BLOB -> "cursor.getBlob(" + column + ")";
            };
            out.append("        item.").append(field.name()).append(" = ").append(read).append(";\n");
        }
        out.append("        return item;\n    }\n");
    }
}
